version: "3.7"

services:
  nginx:
    container_name: ${DOCKER_CONTAINER}-site-nginx
    image: nginx:latest
    ports:
      - "${DOCKER_NGINX_PORT}:80"
      - "${DOCKER_NGINX_PORT_SSL}:443"
    networks:
      - binar
    environment:
        - DOCKER_CONTAINER=tracker
        - DOCKER_PROJECT_DOMAIN=tasks.local
    volumes:
      #- ./docker/nginx/templates:/etc/nginx/templates
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./docker/nginx/logs:/var/log/nginx/
      - ./storage:/storage
      - ./public/docs:/public/docs
#    command: >
#        sh -c "
#          envsubst '\$DOCKER_CONTAINER \$DOCKER_PROJECT_DOMAIN' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/conf.d/default.conf &&
#          nginx -g 'daemon off;'
#        "
    depends_on:
      - php

  php:
    container_name: ${DOCKER_CONTAINER}-site-php
    build:
      context: ./
      dockerfile: docker/fpm/Dockerfile
    working_dir: /api
    expose:
        - "9000"  # üëç –¢–æ–ª—å–∫–æ –¥–ª—è –≤–Ω—É—Ç—Ä–µ–Ω–Ω–µ–π —Å–µ—Ç–∏
#    ports:
#      - "${DOCKER_PROJECT_IP}:8001:9000"
    networks:
      - binar
    restart: always
    volumes:
      - ./.:/api
    environment:
      PHP_IDE_CONFIG: "serverName=${DOCKER_PROJECT_DOMAIN}"

  db:
    container_name: ${DOCKER_CONTAINER}-site-db
    image: mysql:latest
    volumes:
      - binar-db-vol:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    command: [
        "--log_bin_trust_function_creators=1",
        "--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"
    ]
    ports:
      - "${DOCKER_PROJECT_IP}:${DOCKER_DB_PORT}:3306"
    networks:
      - binar
    restart: always

networks:
  binar:
    driver: bridge

volumes:
  binar-db-vol:
